### ISSUE TITLE
feature: Evaluate FUNC7 RGB HSV Conversion

### ISSUE THREAD

**Issue by anna-sara-maria** [august-tengland/DD2480_lab3_TheAlgorithms_Python#10]
### Feature description

CCN: 17 hsv_to_rgb@15-81@.\conversions\rgb_hsv_conversion.py 
Easy function to look at; may have full coverage though

**Comment by august-tengland** [comment]
I don't think we should use this one. you can create three tests, one for each exception (that is not yet tested) however that is about it. The function structure is also very "uninteresting"

**Comment by august-tengland** [comment]
This function can be reconsidered for implementation, I'll reopen the issue and see of somebody wants it.

**Comment by Kaan-wq** [comment]
I'll take this one! Closing this issue and opening 3 new ones
