### ISSUE TITLE
feature: Evaluate FUNC9 Quine Mc Cluskey

### ISSUE THREAD

**Issue by anna-sara-maria** [august-tengland/DD2480_lab3_TheAlgorithms_Python#12]
### Feature description

CCN: 17 selection@84-128@.\boolean_algebra\quine_mc_cluskey.py
Good; 75% test coverage... 26 misses

**Comment by august-tengland** [comment]
This seems feasible to work with

**Comment by Nichvonb** [comment]
I got this one. Opened a new issue #17
