### ISSUE TITLE
feature: Evaluate FUNC11 Inverse of Matrix

### ISSUE THREAD

**Issue by anna-sara-maria** [august-tengland/DD2480_lab3_TheAlgorithms_Python#14]
### Feature description

CNN: 20 inverse_of_matrix@8-155@.\matrix\inverse_of_matrix.py

**Comment by august-tengland** [comment]
I haven't tried branch coverage on this one but it has 12 tests already soooo...

**Comment by dengty1998** [comment]
> I haven't tried branch coverage on this one but it has 12 tests already soooo...

Just ignore this one. The code coverage is 100% according to the tool.
