### ISSUE TITLE
feature: Evaluate FUNC1 Point-to-Polynomial 

### ISSUE THREAD

**Issue by anna-sara-maria** [august-tengland/DD2480_lab3_TheAlgorithms_Python#4]
### Feature description

@linear_algebra/src/polynom_for_points.py , 21CC (3rd in rankings).
Got lots of doctests but maybe not 100% branch coverage?

**Comment by dengty1998** [comment]
coverage is 79%   
missing lines are 35, 39, 42, 97, 107-116
Seems not bad, but need to understand the function to make sure we can have 4 tests.

**Comment by august-tengland** [comment]
I think this is solid, would not mind picking this one.

**Comment by anna-sara-maria** [comment]
I got this one, opening a new issue soon!
