### ISSUE TITLE
feature: Evaluate FUNC2 Red Black Tree

### ISSUE THREAD

**Issue by anna-sara-maria** [august-tengland/DD2480_lab3_TheAlgorithms_Python#5]
### Feature description

@data_structures/binary_tree/red_black_tree  : 19CC (10th in rankings). 
Got one pytest which does insertion before hand, however we could still use it to evaluate existing branch coverage

**Comment by anna-sara-maria** [comment]
This one seems like a looot of work

**Comment by august-tengland** [comment]
We decided that the functions in this class might actually be worth analyzing. I'll reopen this issue until a final decision has been made.

**Comment by august-tengland** [comment]
I'll get this one! Opening new issues shortly.
