### ISSUE TITLE
feature: Evaluate FUNC3 Convert Number to Word

### ISSUE THREAD

**Issue by anna-sara-maria** [august-tengland/DD2480_lab3_TheAlgorithms_Python#6]
### Feature description

CCN: 16 convert@4-105@.\web_programming\convert_number_to_words.py
1 test

**Comment by dengty1998** [comment]
Looks good to me.  
The coverage is 79% which is a little bit high.
Lines12-13, 72-74, 79, 84, 88, 91-102 are missing. 
But there is only one test and it seems not difficult to create more tests to increase the coverage.

**Comment by dengty1998** [comment]
I got this one. Opened a new issue soon.
