### ISSUE TITLE
feature: Evaluate FUNC5 Sequential Minimum Optimization

### ISSUE THREAD

**Issue by anna-sara-maria** [august-tengland/DD2480_lab3_TheAlgorithms_Python#8]
### Feature description

CCN: 16 fit@81-144@.\machine_learning\sequential_minimum_optimization.py
Almost no tests, but relatively hard to test, only one test

**Comment by august-tengland** [comment]
This one seems terrible to work with, I'll close this issue and consider re-opening #5
