### ISSUE TITLE
feature: Evaluate FUNC6 Binomial Heap

### ISSUE THREAD

**Issue by anna-sara-maria** [august-tengland/DD2480_lab3_TheAlgorithms_Python#9]
### Feature description

CCN: 16 delete_min@256-357@.\data_structures\heap\binomial_heap.py 
Quite a few tests, but complex enough so as to require more tests likely

**Comment by dengty1998** [comment]
Coverage is 93% and just missing lines141-144, 292-294, 368, 391, 399-401
Seems bad.
